add option to toggle tooltips
susisu/tree-view-panes pull request #4
Opened 2017-05-31 05:10 UTC by chrisdrackett

2017-05-31 09:36 UTC, susisu requested changes
Looks nice! 👍 

I found there are several points to be fixed before merging.
Can you fix them?

Thanks.

2017-05-31 09:36 UTC, susisu commented on lib/item-view.js
> +    this.showTooltips = atom.config.get(`${CONFIG_PREFIX}showTooltips`);
(related to the comment below)
This initial value should also be set by the controller via some new method (as `setTitle()` is used).

2017-05-31 09:36 UTC, susisu commented on package.json
> +
This empty line should be removed.

2017-05-31 09:36 UTC, susisu commented on lib/item-view.js
> +    this.subscriptions = new CompositeDisposable();
I think this event subscription should be in `item-controller.js`.
Can you move this?

2017-05-31 19:08 UTC, chrisdrackett commented on lib/item-view.js
> +    this.showTooltips = atom.config.get(`${CONFIG_PREFIX}showTooltips`);
done!

2017-05-31 19:08 UTC, chrisdrackett commented on lib/item-view.js
> +    this.subscriptions = new CompositeDisposable();
done!

2017-05-31 19:08 UTC, chrisdrackett commented
@susisu ready for review

2017-05-31 19:09 UTC, chrisdrackett commented on package.json
> +
done!

2017-06-01 03:38 UTC, susisu commented
LGTM! (actually the first one seems to be not fixed, but I will fix it later)
Thank you.

2017-06-01 03:38 UTC, susisu approved these changes

2017-06-01 03:40 UTC, merged